### ISSUE TITLE
vmath lib?

### ISSUE THREAD

**Issue by gwald** [jtsiomb/goat3d#1]
Hi, cool project.
Wanting to try it out but can't figure out which vmath lib you use?
Ie: xform_node.h you have:
#include "vmath/vector.h"
#include "vmath/quat.h"
#include "vmath/matrix.h"

And other places you have:
#include <vmath.h>

I downloaded http://bartipan.net/vmath/
But it has a single header.
Any help would be good.
Cheers

**Comment by jtsiomb** [comment]
Mine! :) https://github.com/jtsiomb/libvmath

including <vmath.h> sounds wrong, and I don't think it shouldn't compile, since all libvmath headers are installed in a vmath subdirectory of $(PREFIX)/include.

**Comment by gwald** [comment]
Hey thanks for the quick reply :)
I didn't think to check your repo.. works, same with libanim
Anyway.. now i'm stuck with the qt5 moc(qt4) stuff on the viewer lol
I'll see if i can port to SDL

Oh, I got it, had to give it the full path, works
MOC = /usr/lib/x86_64-linux-gnu/qt5/bin/moc
I got QT5 linking issues :/
